#!/bin/bash

#@file
#Installs/Uninstalls Fedora Repository 4

# Libs
source ${HOME}/.bash_functions/msgs

# Settings/Vars
v="4.5.1"
fed_name="fedora4" #This will be the ending of the url
tomcat_location="/Library/Tomcat"
data_dir="${HOME}/.fedora4-data" #The data directory where caching and junk is stored.


# Checks
if [ ! -d ${tomcat_location}/webapps ]; then
  bad_msg "Could not find the place to put the file. ${tomcat_location} doesn't exist."
  exit 1
fi

# Check if tomcat is running and if so, stop it.
if [ $(tc running) -eq 1 ]; then
  tc stop
  sleep 2
fi


# Uninstall Fedora
if [ "${1}" == "destroy" ] || [ "${1}" == "rebuild" ]; then
  good_msg "Uninstalling Fedora"

  rm -r ${tomcat_location}/webapps/${fed_name}
  rm ${tomcat_location}/webapps/${fed_name}.war

  #Remove the data directory
  rm -r ${data_dir}
  sed -i '' '/fedora4-data/d' ${tomcat_location}/bin/setenv.sh

  # If destroying, stop here.
  if [ "${1}" == "destroy" ]; then
    exit 0
  fi
fi


# Install Fedora
good_msg "Installing Fedora 4"

curl -Lo ${fed_name}.war https://github.com/fcrepo4/fcrepo4/releases/download/fcrepo-${v}/fcrepo-webapp-${v}.war
mv ${fed_name}.war ${tomcat_location}/webapps

# Set up the data directory
mkdir ${data_dir}
echo 'JAVA_OPTS="$JAVA_OPTS -Dfcrepo.home='${data_dir}'"' >> ${tomcat_location}/bin/setenv.sh

# Fire it up!
tc start

