#!/bin/bash

#@file
#Installs/Uninstalls FFmpeg

# Libs
source ${HOME}/.bash_functions/msgs

# Checks
if [ -z $(which brew) ]; then
  bad_msg "You need to install Homebrew first."
  exit 1
fi

# Uninstall
if [ "${1}" == "destroy" ] || [ "${1}" == "rebuild" ]; then
  good_msg "Uninstalling FFmpeg."
  brew rmtree ffmpeg

  # If destroying, stop here.
  if [ "${1}" == "destroy" ]; then
    exit 0
  fi
fi

# Install
good_msg "Installing FFmpeg."
brew install ffmpeg --with-libvpx --with-libvorbis

