#!/bin/bash

#@file
#Installs/Uninstalls GhostScript

# Libs
source ${HOME}/.bash_functions/msgs

# Checks
if [ -z $(which brew) ]; then
  bad_msg "\nYou need to install Homebrew first.\n"
  exit 1
fi

# Uninstall
if [ "${1}" == "destroy" ] || [ "${1}" == "rebuild" ]; then
  good_msg "Uninstalling GhostScript"
  brew rmtree ghostscript

  # If destroying, stop here.
  if [ "${1}" == "destroy" ] || [ ${?} -gt 0 ]; then
    exit 0
  fi
fi

# Install
good_msg "Installing GhostScript"
brew install ghostscript

