#!/bin/bash

#@file
#Installs/Uninstalls GhostScript

this_dir=$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)
if [ -f ${this_dir}/bootstrap.sh ]; then
  source ${this_dir}/bootstrap.sh
else
  echo -e "\nCouldn't find bootstrap.sh! Ooooh noooo\n"
  exit 1
fi


# Checks
if [ -z $(which brew) ]; then
  bad_msg "\nYou need to install Homebrew first.\n"
  exit 1
fi


#Goooo
case "${1}" in

  'install')
    neutral_msg "Installing GhostScript"
    brew install ghostscript
    ;;

  'uninstall')
    neutral_msg "Uninstalling GhostScript"
    brew rmtree ghostscript
    ;;

  'rebuild')
    $0 uninstall
    sleep 1
    $0 install
    ;;

esac

