#!/bin/bash

#@file
#Installs/Uninstalls Homebrew


this_dir=$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)
if [ -f ${this_dir}/bootstrap.sh ]; then
  source ${this_dir}/bootstrap.sh
else
  echo -e "\nCouldn't find bootstrap.sh! Ooooh noooo\n"
  exit 1
fi


#Goooo
case "${1}" in

  'install')
    neutral_msg "Installing Homebrew"
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

    # Rmtree is used in a lot of other scripts here to remove dependencies
    brew tap beeftornado/rmtree && brew install beeftornado/rmtree/brew-rmtree
    ;;

  'uninstall')
    neutral_msg "Uninstalling Homebrew"
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall)"
    ;;

  'rebuild')
    $0 uninstall
    sleep 1
    $0 install
    ;;

esac

