#!/bin/bash

#@file
#Installs/Uninstalls RVM, Tomcat, Fedora3, Solr4, MySQL

# Settings/Vars
apps=${PWD}

# No uninstall option. Mass uninstallation makes me itchy.

# Install
${apps}/rvm
sleep 2
${apps}/tomcat
sleep 2
${apps}/fedora3
sleep 2
${apps}/solr4
sleep 2
if [ -z $(which brew) ]; then
  ${apps}/homebrew
  sleep 2
fi
${apps}/mysql

