#!/bin/bash

#@file
#Installs/Uninstalls ImageMagick

this_dir=$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)
if [ -f ${this_dir}/bootstrap.sh ]; then
  source ${this_dir}/bootstrap.sh
else
  echo -e "\nCouldn't find bootstrap.sh! Ooooh noooo\n"
  exit 1
fi


# Checks
if [ -z $(which brew) ]; then
  echo -e "\nYou need to install Homebrew first.\n"
  exit 1
fi


#Goooo
case "${1}" in

  'install')
    neutral_msg "Installing ImageMagick."
    brew install imagemagick --with-tiff --with-ghostscript --with-openjpeg
    ;;

  'uninstall')
    neutral_msg "Uninstalling ImageMagick."
    brew rmtree imagemagick
    ;;

  'rebuild')
    $0 uninstall
    sleep 1
    $0 install
    ;;

esac

