#!/bin/bash

#@file
#Installs/Uninstalls LibreOffice

# Libs
source ${HOME}/.bash_functions/msgs

# Checks
if [ -z $(which brew) ]; then
  bad_msg "You need to install Homebrew first."
  exit 1
fi

# Uninstall
if [ "${1}" == "destroy" ] || [ "${1}" == "rebuild" ]; then
  good_msg "Uninstalling LibreOffice."

  brew cask uninstall libreoffice

  # If destroying, stop here.
  if [ "${1}" == "destroy" ]; then
    exit 0
  fi
fi

# Install
good_msg "Installing LibreOffice."

brew cask install libreoffice

