#!/bin/bash

#@file
#Installs/Uninstalls ImageMagick, FFmpeg, GhostScript, Redis, PhantomJS

# Libs
source ${HOME}/.bash_functions/msgs

# Checks
if [ "$(confirm_msg 'Did you install the hydra-stack first? [yN] ')" != "y" ]; then
  neutral_msg "Install the hydra stack first, then get back to me."
  exit 1
fi

if [ -z $(which brew) ]; then
  bad_msg "LIAR. Install the hydra stack!"
  exit 1
fi

# Settings/Vars
apps=${PWD}

# No uninstall option. Mass uninstallation makes me itchy.

# Install
${apps}/redis
${apps}/imagemagick
${apps}/ffmpeg
${apps}/ghostscript
${apps}/phantomjs

