#!/bin/bash

#@file
#Installs/Uninstalls PhantomJS

# Libs
source ${HOME}/.bash_functions/msgs

# Settings/Vars
PHJS_VERSION="2.1.1"
PHJS_FILE="phantomjs-${PHJS_VERSION}-macosx"

# Uninstall
if [ "${1}" == "destroy" ] || [ "${1}" == "rebuild" ]; then
  good_msg "Uninstalling PhantomJS"
  rm /usr/local/bin/phantomjs

  # If destroying, stop here.
  if [ "${1}" == "destroy" ]; then
    exit 0
  fi
fi

# Install
good_msg "Installing PhantomJS"

curl -LO https://bitbucket.org/ariya/phantomjs/downloads/${PHJS_FILE}.zip
unzip ${PHJS_FILE}.zip > /dev/null
cp ${PHJS_FILE}/bin/phantomjs /usr/local/bin
rm -r ${PHJS_FILE}*

