#!/bin/bash

#@file
#Installs/Uninstalls Redis

# Libs
this_dir=$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)
if [ -f ${this_dir}/bootstrap.sh ]; then
  source ${this_dir}/bootstrap.sh
else
  echo -e "\nCouldn't find bootstrap.sh! Ooooh noooo\n"
  exit 1
fi

# Settings/Vars
conf="/usr/local/etc/redis.conf"
pid_file="${HOME}/.redis.pid"
log_file="${HOME}/.redis.log"

# Checks
if [ -z $(which brew) ]; then
  bad_msg "You need to install Homebrew first."
  exit 1
fi

# Functions
function is_running {
  if [ -f "${pid_file}" ]; then
    echo 1
  else
    echo 0
  fi
}

function start {
  if [ $(is_running) == "0" ]; then
    good_msg "Starting Redis"
    echo "" > ${log_file}
    nohup redis-server ${conf} > ${log_file} 2>&1&
    echo "${!}" > ${pid_file}
  fi
}

function stop {
  if [ $(is_running) == "1" ]; then
    good_msg "Stopping Redis"
    kill $(head -n 1 ${pid_file})
    rm ${pid_file}
    sleep 3
  fi
}

function restart {
  stop
  sleep 1
  start
}

function install {
  good_msg "Installing Redis."
  brew install redis
}

function uninstall {
  good_msg "Uninstalling Redis."
  brew rmtree redis
}

#Goooo
case "${1}" in
  'running')
    is_running
    ;;

  'start')
    start
    ;;

  'stop')
    stop
    ;;

  'restart')
    restart
    ;;

  'install')
    install
    ;;

  'uninstall')
    uninstall
    ;;

  'rebuild')
    uninstall
    install
    ;;
esac

