#!/bin/bash

#@file
#Installs/Uninstalls RVM

# Libs
source ${HOME}/.bash_functions/msgs

# Uninstall
if [ "${1}" == "destroy" ] || [ "${1}" == "rebuild" ]; then
  # Uninstall all gems on all rubies, then uninstall the rubies.
  for rubyv in $(rvm list | grep "ruby-*")
  do
    if [[ "${rubyv}" =~ [[:digit:]]\.[[:digit:]]+\.?[[:digit:]]* ]]; then
      rvm use ${BASH_REMATCH}
      if [ ${?} == 0 ]; then
        good_msg "Uninstalling all Gems on Ruby ${BASH_REMATCH}"
        gem uninstall -x --force --all
        gem cleanup
        good_msg "Uninstalling Ruby ${BASH_REMATCH}"
        rvm uninstall ${BASH_REMATCH}
      fi
    fi
  done

  rvm cleanup all

  good_msg "Uninstalling RVM"
  rvm implode
  sed -i .bak '/\.rvm/d' ${HOME}/.bash_profile
  sed -i .bak '/\.rvm/d' ${HOME}/.bashrc
  sed -i .bak '/\.rvm/d' ${HOME}/.zshrc
  sed -i .bak '/\.rvm/d' ${HOME}/.zlogin

  # If destroying, stop here.
  if [ "${1}" == "destroy" ]; then
    exit 0
  fi
fi

# Install
good_msg "Installing RVM"

\curl -L https://get.rvm.io | bash -s stable --auto-dotfiles


