#!/bin/bash

#@file
# Starts/Stops Sidekiq
# Had to abbreviate to not overwrite actual sidekiq command.

# Libs
this_dir=$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)
if [ -f ${this_dir}/bootstrap.sh ]; then
  source ${this_dir}/bootstrap.sh
else
  echo -e "\nCouldn't find bootstrap.sh! Ooooh noooo\n"
  exit 1
fi

# Settings/Vars
pid_file="${HOME}/.sidekiq.pid"

# Functions
function is_running {
  if [ -f "${pid_file}" ]; then
    echo 1
  else
    echo 0
  fi
}

function start {
  rake -n >/dev/null 2>/dev/null
  if [ $? -gt 0 ]; then
    bad_msg "You're not in a Rails project."
    exit 1
  fi

  if [ $(redis running) == "0" ]; then
    neutral_msg "Starting Redis first . . ."
    redis start
    sleep 3
  fi

  if [ $(is_running) == "0" ]; then
    good_msg "Starting Sidekiq"
    bundle exec sidekiq -d -l tmp/sidekiq.log -P ${pid_file}
  fi
}

function stop {
  if [ $(is_running) == "1" ]; then
    good_msg "Stopping Sidekiq"
    kill $(head -n 1 ${pid_file})
    rm ${pid_file}
    sleep 2
  fi
}

function restart {
  stop
  sleep 1
  start
}

#Goooo
case "${1}" in
  'running')
    is_running
    ;;

  'start')
    start
    ;;

  'stop')
    stop
    ;;

  'restart')
    restart
    ;;
esac
