#!/bin/bash

#@file
# Manages Solr 6

# Settings/Vars
minor_v="3.0"
v=6.${minor_v}
filename="solr-${v}"
solr_home="/usr/local/solr"
solr_script="${solr_home}/bin/solr"
pid_file="${HOME}/.solr_pid"

#Goooo
case "${1}" in

  # Is Solr running?
  'running')
    if [ -f "${pid_file}" ]; then
      echo 1
    else
      echo 0
    fi
    ;;

  'start')
    if [ $($0 running) -eq 0 ]; then
      echo -e "\nStarting Solr\n"
      ${solr_script} start
      echo "${!}" > ${pid_file}
    fi
    ;;

  'stop')
    if [ $($0 running) -eq 1 ]; then
      echo -e "\nStopping Solr\n"
      ${solr_script} stop
      rm ${pid_file}
    fi
    ;;

  'restart')
    $0 stop
    sleep 3
    $0 start
    ;;

  'install')
    if [ -d "${solr_home}" ]; then
      echo -e "\n${solr_home} already exists!\n"
      exit 1
    fi

    echo -e "\nInstalling Solr 6\n"

    # Get the files
    curl -fOL https://archive.apache.org/dist/lucene/solr/${v}/${filename}.tgz
    if [ ${?} -gt 0 ]; then
      echo -e "\nFailed to retrieve Solr from the web.\n"
      exit 1
    fi

    tar -xf ${filename}.tgz

    # Add solr home
    mv ${filename} ${solr_home}

    # Remove cruft
    rm ${filename}.tgz

    $0 start
    ;;

  'destroy')
    echo -e "\nUninstalling Solr 6.\n"

    $0 stop
    rm -r ${solr_home}
    ;;

  'rebuild')
    $0 destroy
    sleep 3
    $0 install
    ;;

esac

