#!/bin/bash

#@file
#Installs/Uninstalls Solr 6

# Settings/Vars
minor_v="3.0"
v=6.${minor_v}
filename="solr-${v}"
solr_home="/usr/local/solr"

# Uninstall
if [ "${1}" == "destroy" ] || [ "${1}" == "rebuild" ]; then
  echo -e "\nUninstalling Solr 6.\n"

  ${solr_home}/bin/solr stop
  rm -r ${solr_home}

  # If destroying, stop here.
  if [ "${1}" == "destroy" ]; then
    exit 0
  fi
fi

# Install
echo -e "\nInstalling Solr 6\n"

# Get the files
curl -OL https://archive.apache.org/dist/lucene/solr/${v}/${filename}.tgz
tar -xf ${filename}.tgz

# Add solr home
mv ${filename} ${solr_home}

# Remove cruft
rm ${filename}.tgz

