#!/bin/bash

#@file
#Template for the other scripts

this_dir=$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)
if [ -f ${this_dir}/bootstrap.sh ]; then
  source ${this_dir}/bootstrap.sh
else
  echo -e "\nCouldn't find bootstrap.sh! Ooooh noooo\n"
  exit 1
fi


# Settings/Vars


# Checks

# Functions
function is_running {
}

function start {
}

function stop {
}

function install {
}

function uninstall {
}


#Goooo
case "${1}" in

  'running')
    is_running
    ;;

  'start')
    start
    ;;

  'stop')
    stop
    ;;

  'restart')
    stop
    start
    ;;

  'install')
    install
    ;;

  'uninstall')
    uninstall
    ;;

  'rebuild')
    uninstall
    install
    ;;

esac

