#!/bin/bash

#@file
#Installs/uninstalls Tomcat

# Libs
source ${HOME}/.bash_functions/msgs

# Checks
if [ -z $(which java) ]; then
  bad_msg "You need to install Java!"
  exit 1
fi

# Settings/Vars
major_v="7" #Defaults to lastest version of 7
minor_v="0.70"
v="${major_v}.${minor_v}"
t_dir="apache-tomcat-${v}"
t_file="${t_dir}.tar.gz"

# Uninstall Tomcat
if [ "${1}" == "destroy" ] || [ "${1}" == "rebuild" ]; then
  good_msg "Uninstalling Tomcat."

  # Turn it off, in case it's running.
  /Library/Tomcat/bin/shutdown.sh

  # Remove all the things!
  sudo rm /Library/Tomcat
  rm -r /usr/local/${t_dir}

  # If destroying, stop here.
  if [ "${1}" == "destroy" ]; then
    exit 0
  fi
fi

# Install Tomcat
good_msg "Installing Tomcat v${v}."

target_url="http://apache.mirrors.lucidnetworks.net/tomcat/tomcat-${major_v}/v${v}/bin/${t_file}"
curl -OL ${target_url}
tar -xvf ${t_file}
mv ${t_dir} /usr/local
rm ${t_file}
sudo ln -s /usr/local/${t_dir} /Library/Tomcat
sudo chown -R $(whoami) /Library/Tomcat
sudo chmod +x /Library/Tomcat/bin/*.sh

