#!/bin/bash

#@file
#Installs/uninstalls Tomcat

# Libs
source ${HOME}/.bash_functions/msgs

# Checks
if [ -z $(which java) ]; then
  bad_msg "You need to install Java!"
  exit 1
fi

# Settings/Vars
major_v="7" #Defaults to lastest version of 7
minor_v="0.70"
v="${major_v}.${minor_v}"
t_dir="apache-tomcat-${v}"
t_file="${t_dir}.tar.gz"
tomcat_location="/Library/Tomcat"

# Uninstall Tomcat
if [ "${1}" == "destroy" ] || [ "${1}" == "rebuild" ]; then
  good_msg "Uninstalling Tomcat."

  # Checks if tomcat is already running, and if so turns it off.
  if [ ! -z "$(ps aux | grep tomcat | grep -v grep)" ]; then
    tc stop
  fi

  # Remove all the things!
  sudo rm ${tomcat_location}
  rm -r /usr/local/${t_dir}

  # If destroying, stop here.
  if [ "${1}" == "destroy" ]; then
    exit 0
  fi
fi

# Install Tomcat
good_msg "Installing Tomcat v${v}."

target_url="http://apache.mirrors.lucidnetworks.net/tomcat/tomcat-${major_v}/v${v}/bin/${t_file}"
curl -OL ${target_url}
tar -xvf ${t_file}
mv ${t_dir} /usr/local
rm ${t_file}
sudo ln -s /usr/local/${t_dir} ${tomcat_location}
sudo chown -R $(whoami) ${tomcat_location}
sudo chmod +x ${tomcat_location}/bin/*.sh
echo 'CATALINA_PID=${HOME}/.tomcat_pid' >> ${tomcat_location}/bin/setenv.sh

tc start

